// <auto-generated />
using System;
using DfE.ExternalApplications.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DfE.ExternalApplications.Infrastructure.Migrations.TenantConfig
{
    [DbContext(typeof(TenantConfigDbContext))]
    [Migration("20260506094216_InitialTenantConfig")]
    partial class InitialTenantConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tenantconfig")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DfE.ExternalApplications.Domain.Tenancy.Entities.TenantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tenants", "tenantconfig");
                });

            modelBuilder.Entity("DfE.ExternalApplications.Domain.Tenancy.Entities.TenantFrontendOriginEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Origin")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("TenantFrontendOrigins", "tenantconfig");
                });

            modelBuilder.Entity("DfE.ExternalApplications.Domain.Tenancy.Entities.TenantHostnameEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Hostname")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("TenantHostnames", "tenantconfig");
                });

            modelBuilder.Entity("DfE.ExternalApplications.Domain.Tenancy.Entities.TenantSettingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSecret")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Category", "Target")
                        .IsUnique();

                    b.ToTable("TenantSettings", "tenantconfig");
                });

            modelBuilder.Entity("DfE.ExternalApplications.Domain.Tenancy.Entities.TenantFrontendOriginEntity", b =>
                {
                    b.HasOne("DfE.ExternalApplications.Domain.Tenancy.Entities.TenantEntity", "Tenant")
                        .WithMany("FrontendOrigins")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DfE.ExternalApplications.Domain.Tenancy.Entities.TenantHostnameEntity", b =>
                {
                    b.HasOne("DfE.ExternalApplications.Domain.Tenancy.Entities.TenantEntity", "Tenant")
                        .WithMany("Hostnames")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DfE.ExternalApplications.Domain.Tenancy.Entities.TenantSettingEntity", b =>
                {
                    b.HasOne("DfE.ExternalApplications.Domain.Tenancy.Entities.TenantEntity", "Tenant")
                        .WithMany("Settings")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DfE.ExternalApplications.Domain.Tenancy.Entities.TenantEntity", b =>
                {
                    b.Navigation("FrontendOrigins");

                    b.Navigation("Hostnames");

                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
